name: bloc_provider
description: >-
  Provides bloc to descendant widget (O(1)), and the bloc is disposed appropriately
  by state which the bloc_provider holds internally.
version: 0.5.0
author: Masayuki Ono <mono0926@gmail.com>
homepage: https://github.com/mono0926/bloc_provider
environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
dev_dependencies:
  flutter_test:
    sdk: flutter
  rxdart:
flutter:
