name: bloc_key
description: A new Flutter application.
version: 1.0.0+1
environment:
  sdk: '>=2.0.0-dev.68.0 <3.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  rxdart: ^0.21.0
  simple_logger: ^0.4.0
  bloc_provider:
    path: ../..
dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true
